baseURL = "https://kawat.bangunan.co/"
languageCode = "id"
title = "Pasang Kawat Pagar | Jual dan Pasang Pagar Kawat dan Pengaman"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Kawat Pagar dan Jasa Pasang Kawat Pengaman - Berpengalaman, Profesional, dan Berkualitas"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual kawat pagar", "jasa pasang kawat pagar", "pagar kawat pengaman", "tukang pasang kawat", "pagar kawat anti maling", "pagar kawat berkualitas"]
  base_price = 30000
  price_range = 20000
  free_consultation = true
  service_types = [
  "Pasang Kawat Pagar",
  "Pasang Kawat Duri",
  "Pasang Kawat Harmonika",
  "Pasang Pagar BRC",
  "Pasang Kawat Pengaman"
  ]
  categories = ["Jasa Pasang Kawat", "Pagar Kawat", "Pengaman Kawat"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil tidak memuaskan.",
  "Revisi gratis jika hasil pemasangan tidak rapi."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkasbitung", "Serang"]
  service_output = "Pagar kawat terpasang rapi dan aman sesuai spesifikasi"

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Kawat Pagar Profesional"
  hero_description = "Kami menawarkan berbagai pilihan kawat pagar berkualitas, dengan material yang kuat dan tahan lama. Solusi terbaik untuk meningkatkan keamanan rumah atau properti Anda dengan pemasangan yang rapi dan berpengalaman."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Kawat Pagar"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pasang kawat pagar dengan berbagai jenis dan desain, bahan berkualitas, dan harga terjangkau. Layanan pengukuran dan konsultasi gratis juga tersedia untuk membantu Anda memilih kawat pagar terbaik sesuai kebutuhan." 
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "kawat.bangunan.co menawarkan berbagai pilihan kawat pagar berkualitas dengan desain kuat dan tahan lama. Kami mengutamakan kepuasan pelanggan dengan pemasangan yang rapi, cepat, dan profesional. Pilih kami untuk meningkatkan keamanan rumah atau properti Anda dengan kawat pagar yang fungsional dan kokoh."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Andi|Joko|Eko|Deni|Rudi|Hendra|Agus|Wawan|Rio}"
  message = "{Saya menggunakan layanan pemasangan kawat pagar dari kawat.bangunan.co untuk {rumah|proyek} saya, dan hasilnya {sangat memuaskan|luar biasa|memuaskan}. {Pemasangan|Proses instalasi} {rapi|baik} dan kawat pagarnya {berkualitas tinggi|kokoh|tahan lama}.|Layanan kawat.bangunan.co {sangat membantu|luar biasa|efektif} dalam memilih dan memasang kawat pagar yang {berkualitas|kokoh}.}"
  response = "{Terima kasih atas kepercayaannya! Kami senang dapat menyediakan kawat pagar {berkualitas|unggul|terbaik} untuk {rumah|proyek} Anda.|Kami menghargai kepercayaan Anda. Terima kasih telah memilih layanan kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Ayu|Sari|Lina|Fitri|Diah|Nur|Maya}"
  message = "{kawat.bangunan.co {sangat membantu|mempermudah} dalam {memilih|mencari} dan {memasang|menginstal} kawat pagar untuk {rumah|hunian} saya. Hasilnya {sangat memuaskan|luar biasa} dan sesuai dengan {kebutuhan|keperluan} saya.|Saya {sangat puas|terkesan|senang} dengan kawat pagar yang saya {beli|pesan} dari kawat.bangunan.co. {Kualitas|Mutunya} {terbaik|tahan lama} dan {pemasangannya|instalasinya} {rapi|cepat}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan layanan dan produk kami.|Terima kasih atas ulasan Anda. Kami senang dapat memenuhi kebutuhan Anda!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Agus|Bayu|Faisal|Galih|Rizal|Bambang|Ali|Fajar|Toni}"
  message = "{Kawat pagar dari kawat.bangunan.co {sangat kokoh|berkualitas tinggi} dan {cocok|tepat} untuk proyek {perumahan|komersial} saya. Proses pemasangan {cepat|lancar|profesional} dan {efisien|terjamin}.|Saya {sangat puas|terkesan|senang} dengan layanan pemasangan kawat pagar dari kawat.bangunan.co. Kualitas produknya {kokoh|baik} dan pemasangannya {rapi|cepat}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan kawat pagar {berkualitas|unggul} dengan layanan {terbaik|yang prima}.|Kami senang bisa memenuhi kebutuhan Anda. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Eko|Toni|Hendra|Dedi|Gilang|Ari|Wawan|Gani|Yudi}"
  message = "{Saya {sangat puas|terkesan|senang} dengan kawat pagar dari kawat.bangunan.co. {Kualitas|Mutu} {produk|barangnya} {sangat baik|unggul|luar biasa} dan {pemasangannya|instalasinya} {tahan lama|kokoh} untuk proyek saya.|Kawat pagar dari kawat.bangunan.co {berkualitas tinggi|kokoh} dan sangat sesuai untuk proyek saya.}"
  response = "{Senang mendengar Anda puas dengan kawat pagar kami. Terima kasih atas kepercayaannya!|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih layanan kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Lina|Dewi|Ayu|Sari|Fitri|Maya|Nur|Diah}"
  message = "{Pelayanan kawat.bangunan.co {sangat memuaskan|luar biasa|hebat}. Kawat pagar yang saya {pasang|instal} {berkualitas tinggi|kokoh|tahan lama} dan sesuai dengan {harapan|ekspektasi|keinginan} saya.|Saya {senang|terkesan|puas} dengan layanan dari kawat.bangunan.co. Kawat pagarnya {berkualitas|kokoh|tahan lama} dan sesuai dengan {kebutuhan|proyek} saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani} Anda dengan kawat pagar {terbaik|unggul}.|Kami sangat menghargai ulasan Anda. Terima kasih telah mempercayakan proyek Anda kepada kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Deni|Rizal|Rio|Benny|Yanto|Galih|Toni|Faisal|Wawan}"
  message = "{Kawat pagar dari kawat.bangunan.co {sangat sesuai|tepat|cocok} dengan kebutuhan proyek {renovasi|pembangunan} rumah saya. Proses {pemasangan|instalasi} {cepat|aman|efisien} dan {terjamin|lancar|rapi}.|Saya {puas|terkesan|senang} dengan kawat pagar dari kawat.bangunan.co. Layanan pemasangannya {profesional|cepat|efisien} dan sesuai dengan kebutuhan proyek saya.}"
  response = "{Kami {senang|gembira} mendengar bahwa Anda puas dengan produk kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah mempercayakan proyek Anda kepada kami. Kami senang Anda puas dengan hasilnya.}"
  rating = 4

[[params.tabelItems]]
  name = "Pasang Kawat Pagar"
  price = "30.000 /m"
[[params.tabelItems]]
  name = "Pasang Kawat Duri"
  price = "40.000 /m"
[[params.tabelItems]]
  name = "Pasang Kawat Harmonika"
  price = "50.000 /m"
[[params.tabelItems]]
  name = "Pasang Pagar BRC"
  price = "50.000 /m"
[[params.tabelItems]]
  name = "Pasang Kawat Pengaman"
  price = "50.000 /m"

[params.appliList]
  "Pasang Kawat Pagar" = "area perumahan, pabrik, lahan terbuka"
  "Pasang Kawat Duri" = "pagar pengaman, lahan terbuka, area berkebun"
  "Pasang Kawat Harmonika" = "pagar sekolah, fasilitas umum, lapangan"
  "Pasang Pagar BRC" = "perumahan, kantor, pabrik"
  "Pasang Kawat Pengaman" = "pagar tahan lama, pengaman rumah atau gedung"

[params.kegunaanList]
  "Pasang Kawat Pagar" = "memberikan keamanan tambahan di area rumah atau lahan terbuka"
  "Pasang Kawat Duri" = "mencegah masuknya hewan atau penyusup dengan pagar kawat berduri"
  "Pasang Kawat Harmonika" = "cocok untuk fasilitas umum seperti lapangan atau sekolah"
  "Pasang Pagar BRC" = "pagar kokoh dan tahan lama untuk rumah atau bangunan komersial"
  "Pasang Kawat Pengaman" = "menambah perlindungan pada area dengan risiko keamanan tinggi"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
  title = "Jasa Pasang dan Penjualan Kawat Pagar Berkualitas | "
  highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"